name: Render and Commit Image

on:
  workflow_dispatch:
    inputs:
      post_id:
        description: 'The Reddit Post ID, used as the filename.'
        required: true
      render_payload:
        description: 'The JSON data for the renderer script.'
        required: true

jobs:
  render-and-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          # Ensure you have Pillow, pilmoji in your requirements.txt
          # pip install Pillow pilmoji

      - name: Create output directory
        run: mkdir -p generated-images # Create the directory if it doesn't exist

      - name: Run Renderer
        env:
          # Pass the JSON payload as an environment variable
          RENDERER_PAYLOAD: ${{ github.event.inputs.render_payload }}
        run: |
          # The command is hardcoded to render_conversation, and the output path is constructed from the post_id
          python renderer.py render_conversation generated-images/${{ github.event.inputs.post_id }}.png
      
      - name: Commit and push image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add generated-images/${{ github.event.inputs.post_id }}.png
          # Use 'git diff --quiet' to see if there are staged changes. If not, the commit would fail.
          if ! git diff --staged --quiet; then
            git commit -m "feat: Add rendered image for post ${{ github.event.inputs.post_id }}"
            git push
          else
            echo "No changes to commit. Image might already exist or failed to generate."
          fi