name: Render and Commit Image

on:
  workflow_dispatch:
    inputs:
      post_id:
        description: 'The Reddit Post ID, used as the filename.'
        required: true
      render_payload:
        description: 'The JSON data for the renderer script.'
        required: true

jobs:
  render-and-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        id: setup-python # Give this step an ID to reference its output
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # --- NEW CACHING STEP ---
      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          # The path to the directory to cache. Pip's cache lives here on Linux runners.
          path: ~/.cache/pip
          # The key for the cache. If this key doesn't change, the cache is restored.
          # It's made of the runner's OS, the Python version, and a hash of your requirements file.
          # If you change requirements.txt, the hash changes, and the cache is invalidated.
          key: ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pip-${{ hashFiles('**/requirements.txt') }}
          # A fallback key. If the main key isn't found, it will try to find a cache that matches this.
          # This can be useful for partial cache hits.
          restore-keys: |
            ${{ runner.os }}-python-${{ steps.setup-python.outputs.python-version }}-pip-
      # ------------------------

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create output directory
        run: mkdir -p generated-images

      - name: Run Renderer
        env:
          RENDERER_PAYLOAD: ${{ github.event.inputs.render_payload }}
        run: |
          python renderer.py render_conversation generated-images/${{ github.event.inputs.post_id }}.png
      
      - name: Commit and push image
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add generated-images/${{ github.event.inputs.post_id }}.png
          if ! git diff --staged --quiet; then
            git commit -m "feat: Add rendered image for post ${{ github.event.inputs.post_id }}"
            git push
          else
            echo "No changes to commit. Image might already exist or failed to generate."
          fi