name: Update Reddit Community Status

on:
  schedule:
    - cron: "0 4 * * 1" # Set Monday Status (Monday 00:00 EST)
    - cron: "0 4 * * 2" # Clear Monday Status (Tuesday 00:00 EST)
    - cron: "0 4 * * 6" # Set Saturday Status (Saturday 00:00 EST)
    - cron: "0 4 * * 0" # Clear Saturday Status (Sunday 00:00 EST)

  workflow_dispatch:
    inputs:
      action:
        description: "The action to perform"
        required: true
        type: choice
        options:
          - set-monday
          - set-saturday
          - clear
        default: "clear"

jobs:
  run-script:
    runs-on: ubuntu-latest

    env:
      REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
      REDDIT_SECRET: ${{ secrets.REDDIT_SECRET }}
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}
      REDDIT_REFRESH_TOKEN: ${{ secrets.REDDIT_REFRESH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install praw requests

      - name: Set Monday Status
        if: github.event.schedule == '0 4 * * 1' || github.event.inputs.action == 'set-monday'
        run: python manage_status.py set-monday

      - name: Set Saturday Status
        if: github.event.schedule == '0 4 * * 6' || github.event.inputs.action == 'set-saturday'
        run: python manage_status.py set-saturday

      - name: Clear Status
        if: >-
          (github.event.schedule == '0 4 * * 2' || github.event.schedule == '0 4 * * 0') ||
          github.event.inputs.action == 'clear'
        run: python manage_status.py clear
