name: Update Reddit Community Status

on:
  schedule:
    - cron: "0 4 * * 1"
    - cron: "0 4 * * 2"
    - cron: "0 4 * * 6"
    - cron: "0 4 * * 0"
  workflow_dispatch:
    inputs:
      action:
        description: "Action"
        required: true
        type: choice
        options: [set-monday, set-saturday, clear]
        default: "clear"

jobs:
  run-script:
    runs-on: ubuntu-latest
    env:
      REDDIT_USERNAME: ${{ secrets.REDDIT_USERNAME }}
      REDDIT_PASSWORD: ${{ secrets.REDDIT_PASSWORD }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Python dependencies
        run: pip install playwright

      - name: Install Playwright browsers and dependencies
        run: playwright install --with-deps chromium

      - name: Run Python Script
        run: |
          if [ "${{ github.event.schedule }}" = "0 4 * * 1" ] || [ "${{ github.event.inputs.action }}" = "set-monday" ]; then
            python manage_status.py set-monday
          elif [ "${{ github.event.schedule }}" = "0 4 * * 6" ] || [ "${{ github.event.inputs.action }}" = "set-saturday" ]; then
            python manage_status.py set-saturday
          elif [ "${{ github.event.schedule }}" = "0 4 * * 2" ] || [ "${{ github.event.schedule }}" = "0 4 * * 0" ] || [ "${{ github.event.inputs.action }}" = "clear" ]; then
            python manage_status.py clear
          fi

      - name: Upload Debug Screenshot on Failure
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: debug-screenshot
          path: debug_screenshot.png
